### ISSUE TITLE
Error when run dat2json - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by roman-mukhlygin** [HeartofPhos/exile-export#2]
Hi, I'm getting error at the stage: 

> Run `dat2json /game ./exports ./dat-list.txt`

```
(node:211) UnhandledPromiseRejectionWarning: Error: Command failed: bun_extract_file extract-files "/game" "./temp-33KFKa" "data/BaseItemTypes.dat64" "data/Characters.dat64" "data/GrantedEffects.dat64" "data/GrantedEffectsPerLevel.dat64" "data/MapPins.dat64" "data/NPCs.dat64" "data/NPCTalk.dat64" "data/Quest.dat64" "data/QuestRewardOffers.dat64" "data/QuestRewards.dat64" "data/RecipeUnlockDisplay.dat64" "data/SkillGems.dat64" "data/WorldAreas.dat64" "data/LeagueInfo.dat64" "data/LeagueInfoPanelVersions.dat64"
Could not read _.index.bin
Could not open index

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12)
(node:211) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

How to fix this err?

Game Version: Steam
System: Windows 10
Teminal: PowerShell

**Comment by roman-mukhlygin** [comment]
system: Windows 10
teminal: PowerShell

**Comment by HeartofPhos** [comment]
I believe you didn't set the `POE_GAME_DIR` environment variable before running the container
